# .github/workflows/update_profile_stats.yml
name: Update profile SVGs

on:
  schedule:
    # JST 06:00 → UTC 21:00
    - cron: '0 21 * * *'
  workflow_dispatch: {}

concurrency:
  group: update-profile-svgs
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      PROFILE_STATS_URL: ${{ secrets.PROFILE_STATS_URL }}
      PROFILE_LANGUAGES_URL: ${{ secrets.PROFILE_LANGUAGES_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate secrets
        run: |
          if [ -z "${PROFILE_STATS_URL:-}" ] || [ -z "${PROFILE_LANGUAGES_URL:-}" ]; then
            echo "PROFILE_STATS_URL or PROFILE_LANGUAGES_URL is not set in Secrets"; exit 1
          fi

      - name: Fetch and update SVGs
        run: |
          set -euo pipefail

          PAIRS=$(
            cat <<'EOF'
          __URL1__|img/profile_stats.svg
          __URL2__|img/profile_languages.svg
          EOF
          )

          # 置換（Secretsの値を反映）
          PAIRS="${PAIRS/__URL1__/${PROFILE_STATS_URL}}"
          PAIRS="${PAIRS/__URL2__/${PROFILE_LANGUAGES_URL}}"

          UPDATED=0
          while IFS='|' read -r url dest; do
            tmp="$(mktemp)"
            echo "→ Fetch to: $dest"
            curl -fsSL --retry 3 --retry-delay 2 "$url" -o "$tmp"

            if [ ! -s "$tmp" ]; then
              echo "  ✗ empty file (skip)"; rm -f "$tmp"; continue
            fi

            mkdir -p "$(dirname "$dest")"
            if [ ! -f "$dest" ] || ! cmp -s "$tmp" "$dest"; then
              mv "$tmp" "$dest"
              echo "  ✓ updated: $dest"
              UPDATED=1
            else
              rm -f "$tmp"
              echo "  = no change: $dest"
            fi
          done <<< "$PAIRS"

          if [ $UPDATED -eq 1 ]; then
            echo "UPDATED=1" >> "$GITHUB_ENV"
          fi

      - name: Update marker file
        run: |
          set -euo pipefail
          mkdir -p .github
          date -u +%FT%TZ > .github/last-run.txt

      - name: Commit & Push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/last-run.txt img/profile_stats.svg img/profile_languages.svg
          git commit -m ":books: update profile stats"
          git push
